import { Sidebar } from "@/components";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className="flex flex-row bg-background h-[100vh] justify-stretch">
        <section className="basis-2/12 p-4">
          <Sidebar />
        </section>
        <section className="basis-10/12 py-4 px-8 min-h-full">
          {children}
        </section>
      </body>
    </html>
  );
}
